### PR TITLE
feat(multiple images endpoint): user can update multiple images

### PR DESCRIPTION
**Pull request by malaba6**
**What does this PR do?**
- It allows the user to upload multiple images.

**Description of the task to be completed**
To upload multiple images, the user must put a semi-colon between the images

**Relevant PT Stories:**
[User can upload multiple images](https://www.pivotaltracker.com/story/show/166813795)

**How should this manually be tasted?**
In POSTMAN:

`First post a car with multiple images `  > method `POST`
https://http://localhost:3000/api/v2/car
{
  "state": "new",
  "model" : "Corolla S",
  "manufacturer": "Toyota",
  "type": "Car",
  "price": 10000,
  "photo": "https://malaba6.github.io/Auto-Mart/img/ford.jpg;https://malaba6.github.io/Auto-Mart/img/ford.jpg"
}

**Screenshots:**
ch3-images

### CODE REVIEW

**Comment by nshutijonathan** [comment]
It is well structured

**Comment by harerakalex** [comment]
Your pr is very nice.

**Comment by kazungusafari** [comment]
Everything is okay except the title. You need to add the pivotal tracker id in your PR title

**Comment by billthebuilder** [comment]
Just update the tittle but everything else looks fine
#1233456 tittle

**Pull request merged**
